-- use bookshop;
-- CREATE TABLE books 
-- 	(
-- 		book_id INT NOT NULL AUTO_INCREMENT,
-- 		title VARCHAR(100),
-- 		author_fname VARCHAR(100),
-- 		author_lname VARCHAR(100),
-- 		released_year INT,
-- 		stock_quantity INT,
-- 		pages INT,
-- 		PRIMARY KEY(book_id)
-- 	);

-- INSERT INTO books (title, author_fname, author_lname, released_year, stock_quantity, pages)
-- VALUES
-- ('The Namesake', 'Jhumpa', 'Lahiri', 2003, 32, 291),
-- ('Norse Mythology', 'Neil', 'Gaiman',2016, 43, 304),
-- ('American Gods', 'Neil', 'Gaiman', 2001, 12, 465),
-- ('Interpreter of Maladies', 'Jhumpa', 'Lahiri', 1996, 97, 198),
-- ('A Hologram for the King: A Novel', 'Dave', 'Eggers', 2012, 154, 352),
-- ('The Circle', 'Dave', 'Eggers', 2013, 26, 504),
-- ('The Amazing Adventures of Kavalier & Clay', 'Michael', 'Chabon', 2000, 68, 634),
-- ('Just Kids', 'Patti', 'Smith', 2010, 55, 304),
-- ('A Heartbreaking Work of Staggering Genius', 'Dave', 'Eggers', 2001, 104, 437),
-- ('Coraline', 'Neil', 'Gaiman', 2003, 100, 208),
-- ('What We Talk About When We Talk About Love: Stories', 'Raymond', 'Carver', 1981, 23, 176),
-- ("Where I'm Calling From: Selected Stories", 'Raymond', 'Carver', 1989, 12, 526),
-- ('White Noise', 'Don', 'DeLillo', 1985, 49, 320),
-- ('Cannery Row', 'John', 'Steinbeck', 1945, 95, 181),
-- ('Oblivion: Stories', 'David', 'Foster Wallace', 2004, 172, 329),
-- ('Consider the Lobster', 'David', 'Foster Wallace', 2005, 92, 343);
-- select *,CONCAT(author_fname,' ',author_lname) as 'full_name' from books;
-- select substring('Hello World',1,4)
-- select substring('Hello World',7)
-- select substring(title,1,5) from books
-- use bookshop;
-- select concat(substring(title,1,10),"....") from books
-- select REPLACE('www.sql.com','w','Ww')  
-- select REPLACE ('cheese breed coffee milk',' ',' and ')
-- select REPLACE(title,' ','_') from books
-- select REVERSE("Hello") 
-- select concat(author_fname, reverse(author_fname)) from book 
-- select char_length('Hello World')
-- select char_length(title) from books
-- select LOWER("Hello World") 
-- select INSERT("Hello World",6,0,'there')
--  select INSERT("Hello World",6,6,'there')
-- select right('omghaha',3)
-- select repeat('ha',4);
-- select trim('   san antonio   ')
-- select trim(leading '.' from '......san antonio..')
-- select trim(both '.' from '......san antonio..')
-- select replace(title,' ','->') from books
-- select author_lname as 'Forward',reverse(author_lname) as 'Backward' from books
-- select UPPER(CONCAT(author_fname,' ',author_lname)) as 'full name in caps' from books
-- select CONCAT(title,' was released in ',released_year) from books
-- select title,char_length(title) from books
select CONCAT(substr(title,1,10),'...') AS 'short_titles' ,  concat(author_lname,',',author_fname) as author ,concat('This is the stock availiable ',stock_quantity) as stocks from books 